--------------------------------------------------------------------------------
{-|	Module      :  WxcClasses
	Copyright   :  Copyright (c) Daan Leijen 2003, 2004
	License     :  wxWidgets

	Maintainer  :  wxhaskell-devel@lists.sourceforge.net
	Stability   :  provisional
	Portability :  portable

Haskell class definitions for the wxWidgets C library (@wxc.dll@).

Do not edit this file manually!
This file was automatically generated by wxDirect.

From the files:

  * @C:\Users\-\AppData\Roaming\cabal\i386-windows-ghc-7.8.3\wxc-0.91.0.0\include\wxc.h@

And contains 3825 methods for 253 classes.
-}
--------------------------------------------------------------------------------
module Graphics.UI.WXCore.WxcClasses
    ( -- * Re-export
      module Graphics.UI.WXCore.WxcClassesAL
    , module Graphics.UI.WXCore.WxcClassesMZ
    , module Graphics.UI.WXCore.WxcClassTypes
    ) where

import Graphics.UI.WXCore.WxcClassesAL
import Graphics.UI.WXCore.WxcClassesMZ
import Graphics.UI.WXCore.WxcClassTypes

